#!/usr/bin/env bash

app=$( cd "$(dirname "$0")" ; pwd -P )
source "${app}/src/txt.sh"

# Setup python virtual-env for setting up dependencies
note "Checking virtualenv installation.."
sudo -H pip install -qIU --no-warn-conflicts virtualenv
is_ok

# Create a python virtual environment
note "Creating virtual environment.."
virtualenv -q .venv
is_ok

# Enable the virtual environment
note "Activating environment.."
# TODO: should this be done using src/commonn.sh?
source "${app}/.venv/bin/activate"
is_ok

# Then install with pip will be inside that virtual environment
note "Installing requirements.."
pip install -qIr requirements.txt
is_ok
