#!/usr/bin/env bash

app=$( cd "$(dirname "$0")" ; pwd -P )
source "${app}/src/txt.sh"
source "${app}/src/common.sh"

# Run the playbook
if [[ -x "${ANSIBLE_PLAYBOOK}" ]]
then
    AWS_PROFILE=${PROFILE} ${ANSIBLE_PLAYBOOK} launch.yml --extra-vars="@$1" -v
fi
