#!/usr/bin/env bash
CWD="$(dirname "$0")"
source $CWD/utils/common.sh

# Run the playbook
if [[ -x "$ANSIBLE_PLAYBOOK" ]]
then
    AWS_PROFILE=$PROFILE $ANSIBLE_PLAYBOOK launch.yml --extra-vars="@$1" -v
fi
