#!/usr/bin/env bash

app=$( cd "$(dirname "$0")" ; pwd -P )
source "${app}/src/txt.sh"
source "${app}/src/common.sh"

# App name
PROJECT_NAME=$(grep 'project_name' $1 | tail -n1 | cut -d : -f 2 | awk '{$1=$1;print}');

while true; do
    read -p "Do you wish to terminate all the AWS resources launched against ${PROJECT_NAME} (Y/N) " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

# Run the playbook
if [[ -x "${ANSIBLE_PLAYBOOK}" ]]
then
    AWS_PROFILE=${PROFILE} ${ANSIBLE_PLAYBOOK} teardown.yml --extra-vars="@$1" -v
fi
