# Refer to https://docs.docker.com/install/linux/docker-ee/rhel/#set-up-the-repository

---

# Currently support Amazon AMIs and RedHat Enterprise Linux distros
# Add your own distro specific tasks to target others.
- name: Run the RHEL based install for Amazon AMIs
  include: "RHEL.yml"
  when: ansible_distribution == "Amazon" or ansible_distribution == "RedHat"