---

- name: Enable docker
  service:
    enabled=yes
    name=docker
  listen: config docker

- name: Restart docker
  service:
    name=docker
    state=restarted
  register: restart_status
  until: restart_status is success
  retries: 3
  delay: 20
  listen: config docker
  